// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: hello.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PsqlService_SelectData_FullMethodName = "/myapp.PsqlService/SelectData"
)

// PsqlServiceClient is the client API for PsqlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PsqlServiceClient interface {
	SelectData(ctx context.Context, in *SelectDataRequest, opts ...grpc.CallOption) (*SelectDataResponse, error)
}

type psqlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPsqlServiceClient(cc grpc.ClientConnInterface) PsqlServiceClient {
	return &psqlServiceClient{cc}
}

func (c *psqlServiceClient) SelectData(ctx context.Context, in *SelectDataRequest, opts ...grpc.CallOption) (*SelectDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectDataResponse)
	err := c.cc.Invoke(ctx, PsqlService_SelectData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PsqlServiceServer is the server API for PsqlService service.
// All implementations must embed UnimplementedPsqlServiceServer
// for forward compatibility.
type PsqlServiceServer interface {
	SelectData(context.Context, *SelectDataRequest) (*SelectDataResponse, error)
	mustEmbedUnimplementedPsqlServiceServer()
}

// UnimplementedPsqlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPsqlServiceServer struct{}

func (UnimplementedPsqlServiceServer) SelectData(context.Context, *SelectDataRequest) (*SelectDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectData not implemented")
}
func (UnimplementedPsqlServiceServer) mustEmbedUnimplementedPsqlServiceServer() {}
func (UnimplementedPsqlServiceServer) testEmbeddedByValue()                     {}

// UnsafePsqlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PsqlServiceServer will
// result in compilation errors.
type UnsafePsqlServiceServer interface {
	mustEmbedUnimplementedPsqlServiceServer()
}

func RegisterPsqlServiceServer(s grpc.ServiceRegistrar, srv PsqlServiceServer) {
	// If the following call pancis, it indicates UnimplementedPsqlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PsqlService_ServiceDesc, srv)
}

func _PsqlService_SelectData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PsqlServiceServer).SelectData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PsqlService_SelectData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PsqlServiceServer).SelectData(ctx, req.(*SelectDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PsqlService_ServiceDesc is the grpc.ServiceDesc for PsqlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PsqlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myapp.PsqlService",
	HandlerType: (*PsqlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectData",
			Handler:    _PsqlService_SelectData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
